
Create table DISTRICT
(
DISTRICT_ID VARCHAR (10),
DISTRICTNAME VARCHAR (50) NOT NULL
Constraint D_ID Primary Key (DISTRICT_ID)
)



Create table PROPERTYTYPE
(
PROPERTYTYPEID  VARCHAR (10),
PROPERTYTYPENAME VARCHAR (30) NOT NULL
Constraint T_ID Primary Key (PROPERTYTYPEID)
)



Create table NEWS
(
NEWSID VARCHAR (10),
NAME  VARCHAR (50) NOT NULL,
DESCRIPTIONNEWS VARCHAR (500) NOT NULL,
PUBLISHINGDAY SMALLDATETIME NOT NULL,
KEYWORDS  VARCHAR (50) NOT NULL
Constraint N_ID Primary Key (NEWSID)
)




Create table INDUSTRY
(
INDUSTRYID VARCHAR (10),
INDUSTRYNAME VARCHAR (30) NOT NULL
Constraint I_ID Primary Key (INDUSTRYID)
)


Create table USERROLE
(
ROLEID VARCHAR (10),
ROLENAME VARCHAR (30) NOT NULL,
ROLEDESCRIPTION VARCHAR (100) NOT NULL
Constraint R_ID Primary Key (ROLEID)
)


Create table FEEDBACK
(
FEEDBACKID VARCHAR (10),
CUSTOMERNAME VARCHAR (30) NOT NULL,
EMAIL VARCHAR (20) NOT NULL,
FEEDBACK VARCHAR (100) NOT NULL,
PHONE VARCHAR (10) NOT NULL
Constraint F_ID Primary Key (FEEDBACKID)
)


Create table ACCOUNTTYPE
(
ACCOUNTTYPEID VARCHAR (10),
ACCOUNTTYPENAME VARCHAR (30) NOT NULL
Constraint AT_ID Primary Key (ACCOUNTTYPEID)
)








Create table ACCOUNT
(
ACCOUNTID VARCHAR (10),
DISPLAYNAME VARCHAR (50)NOT NULL,
ACCOUNTPASSWORD VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
PHONE VARCHAR (10) NOT NULL,
APPROVALSTATUS VARCHAR (10) NOT NULL,
ACCOUNTADDRESS VARCHAR (20) NOT NULL,
ROLEID VARCHAR (10)NOT NULL,
ACCOUNTTYPEID VARCHAR (10) NOT NULL 
Constraint A_ASDSID Primary Key (ACCOUNTID),
Constraint RASD_ID Foreign Key (ROLEID) References [USERROLE] ([ROLEID]),
Constraint AMO Foreign Key (ACCOUNTTYPEID) References [ACCOUNTTYPE] ([ACCOUNTTYPEID])
)



Create table MONTHLYPAYMENT
(
MPAYMENTID VARCHAR (10),
ACCOUNTID VARCHAR (10) NOT NULL,
PROPERTYTYPEID VARCHAR (10) NOT NULL,
PAYMENTMONTH SMALLINT NOT NULL,
PAYMENTYEAR SMALLINT NOT NULL
Constraint MP_ID Primary Key (MPAYMENTID),
Constraint AID Foreign Key (ACCOUNTID) References [ACCOUNT] ([ACCOUNTID])
)




Create table COMPANYACCOUNT
(
COMPANYACCOUNTID VARCHAR (10),
ACCOUNTID VARCHAR (10)NOT NULL,
ACCOUNTTYPEID VARCHAR (10) NOT NULL,
DISPLAYNAME VARCHAR (50)NOT NULL,
COMPANYPASSWORD VARCHAR (50) NOT NULL,
COMPANYDESCRIPTION VARCHAR (50) NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
INDUSTRYID VARCHAR (10) NOT NULL,
PHONE VARCHAR (10) NOT NULL,
FOUNDINGYEAR SMALLINT NOT NULL,
NUMBEROFEMPLOYEES SMALLINT NOT NULL,
PROPERTYTYPEID VARCHAR (10) NOT NULL
Constraint MPAID Primary Key (COMPANYACCOUNTID),
Constraint A_aD Foreign Key (ACCOUNTID) References [ACCOUNT] ([ACCOUNTID]),
Constraint AO1 Foreign Key (ACCOUNTTYPEID) References [ACCOUNTTYPE] ([ACCOUNTTYPEID]),
Constraint AOA Foreign Key (INDUSTRYID) References [INDUSTRY] ([INDUSTRYID]),
Constraint AL Foreign Key (PROPERTYTYPEID) References [PROPERTYTYPE] ([PROPERTYTYPEID])
)





Create table PROPERTY
(
PROPERTYID VARCHAR (10),
PROPERTYNAME VARCHAR (50)NOT NULL,
PROPERTYDESCRIPTION VARCHAR (50) NOT NULL,
PRICE VARCHAR (10) NOT NULL,
PROPERTYADDRESS VARCHAR (50) NOT NULL,
DISTRICT_ID VARCHAR (10) NOT NULL,
NUMBEROFROOMS SMALLINT NOT NULL,
PROPERTYTYPEID VARCHAR (10) NOT NULL,
ACCOUNTID VARCHAR (10)NOT NULL,
APRROVALSTATUS VARCHAR (10) NOT NULL,
TIMEPOST SMALLDATETIME NOT NULL
Constraint MPAAID Primary Key (PROPERTYID),
Constraint A_DASDD Foreign Key (DISTRICT_ID) References [DISTRICT] ([DISTRICT_ID]),
Constraint ALO Foreign Key (PROPERTYTYPEID) References [PROPERTYTYPE] ([PROPERTYTYPEID]),
Constraint AWE_aD Foreign Key (ACCOUNTID) References [ACCOUNT] ([ACCOUNTID])
)









