Create table ORIGINALCOUNTRY
(
ORIGINID VARCHAR (10),
ORIGIN VARCHAR (10)NOT NULL
Constraint O_ID Primary Key (ORIGINID)
)


Create table PRODUCTTYPE
(
PRODUCTTYPEID VARCHAR (10),
PRODUCTTYPENAME VARCHAR (50)NOT NULL
Constraint PT_ID Primary Key (PRODUCTTYPEID)
)



Create table BRAND
(
BRANDID VARCHAR (10),
BRANDNAME VARCHAR (50)NOT NULL,
FOUNDINGDATE SMALLDATETIME NOT NULL,
COMPANYSIZE SMALLINT NOT NULL,
PHONE VARCHAR (10) NOT NULL,
EMAIL VARCHAR (20) NOT NULL
Constraint B_ID Primary Key (BRANDID)
)


Create table MODEL
(
MODELID VARCHAR (10),
MODELNAME VARCHAR (50)NOT NULL,
BRANDID VARCHAR (10) NOT NULL,
PRODUCTTYPEID VARCHAR (10) NOT NULL
Constraint M_ID Primary Key (MODELID),
Constraint ADA Foreign Key (BRANDID) References [BRAND] ([BRANDID]),
Constraint AMA Foreign Key (PRODUCTTYPEID) References [PRODUCTTYPE] ([PRODUCTTYPEID])
)



Create table NEWS
(
NEWSID VARCHAR (10),
NEWSNAME VARCHAR (50)NOT NULL,
NEWSDESCRIPTION VARCHAR (50) NOT NULL,
PUBLISHINGDATE SMALLDATETIME NOT NULL,
KEYWORDS VARCHAR (20) NOT NULL
Constraint N_ID Primary Key (NEWSID)
)



Create table FEEDBACK
(
FEEDBACKID VARCHAR (10),
NAME VARCHAR (50)NOT NULL,
EMAIL VARCHAR (50) NOT NULL,
PHONE VARCHAR (10) NOT NULL,
FEEDBACK VARCHAR (100) NOT NULL
Constraint FB_ID Primary Key (FEEDBACKID)
)

Create table USERROLE
(
USERROLEID VARCHAR (10),
USERROLE VARCHAR (50)NOT NULL,
USERROLEDESCRIPTION VARCHAR (50) NOT NULL
Constraint UR_ID Primary Key (USERROLEID)
)



Create table PURCHASEDTYPE
(
PURCHASEDTYPEID VARCHAR (10),
PURCHASEDTYPE VARCHAR (50) NOT NULL
Constraint PTA_ID Primary Key (PURCHASEDTYPEID)
)


Create table PROMOTION
(
PROMOTIONID VARCHAR (10),
PROMOTIONNAME VARCHAR (50) NOT NULL,
PERCENTAGE VARCHAR (10) NOT NULL,
STARTINGDAY SMALLDATETIME NOT NULL,
ENDINGDAY SMALLDATETIME NOT NULL,
PROMOTIONTYPE VARCHAR (10),
PROMOTIONDESCRIPTION VARCHAR (100) NOT NULL,
PROMOTIONSTATUS VARCHAR (50) NOT NULL
Constraint PM_ID Primary Key (PROMOTIONID)
)


Create table GUESTACCOUNT
(
GUESTACCOUNTID VARCHAR (10),
DISPLAYNAME VARCHAR (50) NOT NULL,
GUESTACCOUNTPASSWORD VARCHAR (10) NOT NULL,
EMAIL VARCHAR (10) NOT NULL,
PHONE VARCHAR (10) NOT NULL,
GA_ADDRESS VARCHAR (20) NOT NULL
Constraint GA_ID Primary Key (GUESTACCOUNTID)
)



Create table PRODUCTS
(
PRODUCTSID VARCHAR (10),
PRODUCTSNAME VARCHAR (50) NOT NULL,
PRODUCTTYPEID VARCHAR (10) NOT NULL,
PURCHASEDTYPEID VARCHAR (10) NOT NULL,
BRANDID VARCHAR (10) NOT NULL,
BUYINGPRICE MONEY NOT NULL,
SELLINGPRICE MONEY NOT NULL,
PRODUCTDESCRIPTION VARCHAR (50) NOT NULL,
RECEIVEDDATE SMALLDATETIME NOT NULL,
MODELID VARCHAR (10) NOT NULL,
ORIGINID VARCHAR (10) NOT NULL
Constraint PD_ID Primary Key (PRODUCTSID),
Constraint PAAASDD Foreign Key (PRODUCTTYPEID) references [PRODUCTTYPE]([PRODUCTTYPEID]), 
Constraint PAASDAAD Foreign Key (PURCHASEDTYPEID) references [PURCHASEDTYPE]([PURCHASEDTYPEID]), 
Constraint PAD Foreign Key (BRANDID) references [BRAND]([BRANDID]),
Constraint MADAD Foreign Key (MODELID) references [MODEL]([MODELID]),
Constraint MADADAD Foreign Key (ORIGINID) references [ORIGINALCOUNTRY]([ORIGINID]) 
)



Create table INSTALLMENTPOLICY
(
INSTALLMENTPOLICYID VARCHAR (10) NOT NULL,
PRODUCTSID VARCHAR (10) NOT NULL,
INSTALLMENTPOLICY VARCHAR (100) NOT NULL,
PREPAYMENTAMOUNT MONEY NOT NULL
Constraint IP_ID Primary Key (INSTALLMENTPOLICYID),
Constraint PRODUCTSID Foreign Key (PRODUCTSID) references [PRODUCTS]([PRODUCTSID]) 
)







Create table USERACCOUNT
(
USERACCOUNTID VARCHAR (10),
USERROLEID VARCHAR (10)NOT NULL,
DISPLAYNAME VARCHAR (50) NOT NULL,
USERPASSWORD VARCHAR (10) NOT NULL, 
EMAIL VARCHAR (50) NOT NULL,
PHONE VARCHAR (10) NOT NULL,
USERADDRESS VARCHAR (50) NOT NULL 
Constraint UA_ID Primary Key (USERACCOUNTID),
Constraint RASDA Foreign Key (USERROLEID) References [USERROLE] ([USERROLEID])
)





Create table MONTHLYPROMOTION
(
PROMOTIONID VARCHAR (10),
PRODUCTSID VARCHAR (10)NOT NULL,
MONTHYEAR SMALLDATETIME NOT NULL
Constraint A_ASSD Primary Key (MONTHYEAR),
Constraint RASD_ID Foreign Key (PROMOTIONID) References [PROMOTION] ([PROMOTIONID]),
Constraint AMO Foreign Key (PRODUCTSID) References [PRODUCTS] ([PRODUCTSID])
)




Create table ORDERRECEIPT
(
ORDERRECEIPTID VARCHAR (10),
GUESTACCOUNTID VARCHAR (10)NOT NULL,
CREATEDDATE SMALLDATETIME  NOT NULL,
PAYMENTSTATUS VARCHAR (50) NOT NULL,
PRICE MONEY NOT NULL,
SERVIINGEMPLOYEE VARCHAR (10) NOT NULL,
PURCHASEDTYPEID VARCHAR (10) NOT NULL
Constraint A_ASDSIASDD Primary Key (ORDERRECEIPTID),
Constraint RASD_ADID Foreign Key (GUESTACCOUNTID) References [GUESTACCOUNT] ([GUESTACCOUNTID]),
Constraint AMADO Foreign Key (PURCHASEDTYPEID) References [PURCHASEDTYPE] ([PURCHASEDTYPEID])
)


Create table ORDERDETAIL
(
ORDERDETAILID VARCHAR(10),
ORDERRECEIPTID VARCHAR (10)NOT NULL,
PRODUCTSID VARCHAR (10)NOT NULL
Constraint A Primary Key (ORDERDETAILID),
Constraint A_ASDADSAASDD Foreign Key (ORDERRECEIPTID) References [ORDERRECEIPT]([ORDERRECEIPTID]),
Constraint RASD_ADIDASDD Foreign Key (PRODUCTSID) References [PRODUCTS] ([PRODUCTSID])
)



Create table INSTALLMENTPAYMENTTYPE
(
INSTALLMENTPAYMENTTYPEID VARCHAR (10) NOT NULL, 
INSTALLMENTPAYMENTTYPENAME VARCHAR (10) NOT NULL
Constraint IPAD_ID Primary Key (INSTALLMENTPAYMENTTYPEID)
)



Create table INSTALLMENTPAYMENTRECEIPT
(
INSTALLMENTPAYMENTRECEIPTID VARCHAR (10),
PURCHASEDTYPEID VARCHAR (10) NOT NULL,
PURCHASEDDAY SMALLDATETIME NOT NULL,
CUSTOMERNAME VARCHAR (50) NOT NULL,
CUSTOMERIDENITYCARD VARCHAR (10) NOT NULL,
CUSTOMERDOB SMALLDATETIME NOT NULL,
GUESTACCOUNTID VARCHAR (10)NOT NULL, 
PHONE VARCHAR (10) NOT NULL,
GUESTADDRESS VARCHAR (50) NOT NULL,
PRODUCTSID VARCHAR (10) NOT NULL,
ORDERDETAILID VARCHAR (10) NOT NULL,
PER_INSTALLMENTPAYMENT MONEY NOT NULL,
INSTALLMENTPAYMENTTYPEID VARCHAR (10) NOT NULL, 
DELIVERYEMPLOYEE VARCHAR (10) NOT NULL,
RECEPITEMPLOYEE VARCHAR (10) NOT NULL, 
AMOUNT MONEY  NOT NULL,
NOTE VARCHAR (50) NOT NULL
Constraint IPR_ID Primary Key (INSTALLMENTPAYMENTRECEIPTID),
Constraint RASD_ADDASDD Foreign Key (PURCHASEDTYPEID) References [PURCHASEDTYPE] ([PURCHASEDTYPEID]),
Constraint RASD_AASDD Foreign Key (GUESTACCOUNTID) References [GUESTACCOUNT] ([GUESTACCOUNTID]), 
Constraint RASDASDD Foreign Key (PRODUCTSID) References [PRODUCTS] ([PRODUCTSID]), 
Constraint RADASDD Foreign Key (INSTALLMENTPAYMENTTYPEID) References [INSTALLMENTPAYMENTTYPE] ([INSTALLMENTPAYMENTTYPEID]), 
Constraint RAAAADASDD Foreign Key (ORDERDETAILID) References [ORDERDETAIL] ([ORDERDETAILID]) 
)


Create table INSTALLMENTPAYMENTMANAGEMENT 
(
EMPLOYEE VARCHAR (50) NOT NULL,
INSTALLMENTPAYMENTRECEIPTID VARCHAR (10) NOT NULL,
PAYMENTDAY SMALLDATETIME NOT NULL,
AMOUNT MONEY  NOT NULL,
REMANINGTIME SMALLDATETIME NOT NULL,
REMAININGMONEY MONEY NOT NULL,
NOTE VARCHAR (50) NOT NULL
Constraint A_ASDSASDD Primary Key (EMPLOYEE),
Constraint RASDASDASDID Foreign Key (INSTALLMENTPAYMENTRECEIPTID) References [INSTALLMENTPAYMENTRECEIPT] ([INSTALLMENTPAYMENTRECEIPTID])
)




Create table NORMALPAYMENTRECEIPT  
(
NORMALPAYMENTRECEIPTID VARCHAR (10) NOT NULL,
PURCHASEDTYPEID VARCHAR (10) NOT NULL,
PURCHASEDDAY SMALLDATETIME NOT NULL,
PRODUCTSID VARCHAR (10) NOT NULL,
CUSTOMERNAME VARCHAR (50) NOT NULL,
CUSTOMERIDENITYCARD VARCHAR (10) NOT NULL,
CUSTOMERDOB SMALLDATETIME NOT NULL,
GUESTACCOUNTID VARCHAR (10)NOT NULL, 
PHONE VARCHAR (10) NOT NULL,
GUESTADDRESS VARCHAR (50) NOT NULL,
AMOUNT MONEY  NOT NULL,
ORDERRECEIPTID VARCHAR (10) NOT NULL,
DELIVERYEMPLOYEE VARCHAR (10) NOT NULL,
RECEPITEMPLOYEE VARCHAR (10) NOT NULL, 
NOTE VARCHAR (50) NOT NULL
Constraint A_ASAASDD Primary Key (NORMALPAYMENTRECEIPTID),
Constraint RAD_SDD Foreign Key (PURCHASEDTYPEID) References [PURCHASEDTYPE] ([PURCHASEDTYPEID]),
Constraint SDASDAS Foreign Key (ORDERRECEIPTID) References [ORDERRECEIPT] ([ORDERRECEIPTID]),
Constraint RASDASDDASDD Foreign Key (PRODUCTSID) References [PRODUCTS] ([PRODUCTSID])
)



